/* build-page.js — splices the three kernel sources VERBATIM into erdos290.html, between the
 * hand-authored anchors. The mfg-cap pattern (research/mfg-cap/tools/build-artifact.js), applied
 * in place: the page stays hand-written; ONLY the span between the ERDOS_KERNELS anchors is
 * generated, and each file inside it sits between BEGIN/END VERBATIM markers so the battery
 * (tests/test-page.js) can slice the embedded bytes back out and assert they equal the
 * sources on disk (C50: the relation page↔kernel is computed and gated, never transcribed).
 *
 * The wrapper is a CommonJS shim resolving require() BY BASENAME against the module table the
 * page defines before the anchors ('path'.join collapses to its last argument). Sources are
 * spliced in dependency order. Import this file for {B, E, WRAP_HEAD, WRAP_TAIL, SOURCES,
 * build}; running it as a script rewrites the page (guarded, so importing has no side effect).
 */
'use strict';
const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const PAGE = path.join(HERE, '..', 'erdos290.html');

const SOURCES = ['rational.js', 'galois-exceptions.js', 'theorem-live.js', 'kernel.js'];
/* data files kernel code reads through the fs shim; spliced as JSON string literals so the
   battery can JSON.parse the literal back and byte-compare with the file */
const DATA = ['tail-deltas.json'];
const DATA_HEAD = n => `__data('${n}', `;
const DATA_TAIL = ');\n';

const A_BEGIN = '/*@@ERDOS_KERNELS_BEGIN@@*/';
const A_END = '/*@@ERDOS_KERNELS_END@@*/';
const B = n => `/* ==== BEGIN VERBATIM ${n} ==== */\n`;
const E = n => `/* ==== END VERBATIM ${n} ==== */`;
const WRAP_HEAD = n => `__def('${n}', function (module, exports, require, __dirname) {\n`;
const WRAP_TAIL = '\n});\n';

function splice() {
  const data = DATA.map(n => {
    const raw = fs.readFileSync(path.join(HERE, n), 'utf8');
    return B(n) + DATA_HEAD(n) + JSON.stringify(raw) + DATA_TAIL + E(n);
  });
  const code = SOURCES.map(n => {
    const src = fs.readFileSync(path.join(HERE, n), 'utf8');
    return B(n) + WRAP_HEAD(n) + src + WRAP_TAIL + E(n);
  });
  return data.concat(code).join('\n');
}

function build(html) {
  const i = html.indexOf(A_BEGIN), j = html.indexOf(A_END);
  if (i < 0 || j < 0 || j < i) throw new Error('page lost its ERDOS_KERNELS anchors');
  return html.slice(0, i + A_BEGIN.length) + '\n' + splice() + '\n' + html.slice(j);
}

module.exports = { B, E, WRAP_HEAD, WRAP_TAIL, DATA_HEAD, DATA_TAIL, SOURCES, DATA,
                   A_BEGIN, A_END, build, PAGE };

/* The pin record: computed sha256 of every spliced source, written on every build (C50 — a
   generated relation, never transcribed). Two consumers: tests/test-page.js gates its
   freshness, and tools/check-narration.js derives from it that narration hits INSIDE these
   pinned bytes are NOTEs naming this record rather than failures (its own policy for spliced
   kernels a committed measurement pins — the mfg-cap precedent). */
const PINS = path.join(HERE, '..', '..', '..', 'research', 'challenges', 'erdos290',
  'page-splice-pins.json');

function pinsRecord() {
  const crypto = require('crypto');
  const pins = {};
  for (const n of SOURCES.concat(DATA)) {
    const bytes = fs.readFileSync(path.join(HERE, n));
    pins['site/technical-reports/erdos290/' + n] =
      crypto.createHash('sha256').update(bytes).digest('hex');
  }
  return {
    what: 'sha256 of every source build-page.js splices verbatim into ' +
      'research/challenges/erdos290.html. Generated by the builder on every run; ' +
      'byte-gate is tests/test-page.js (A1 + A3). Regenerate by running the builder.',
    pins,
  };
}

module.exports.PINS = PINS;
module.exports.pinsRecord = pinsRecord;

if (require.main === module) {
  const before = fs.readFileSync(PAGE, 'utf8');
  const after = build(before);
  fs.writeFileSync(PAGE, after);
  fs.writeFileSync(PINS, JSON.stringify(pinsRecord(), null, 1) + '\n');
  const crypto = require('crypto');
  const sha = s => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);
  console.log(`spliced ${SOURCES.length} kernels into ${path.basename(PAGE)}  ` +
    `${before.length} -> ${after.length} bytes  sha256 ${sha(after)}  (+ pins record)`);
  for (const n of SOURCES) {
    const s = fs.readFileSync(path.join(HERE, n), 'utf8');
    console.log(`  ${n}  ${s.length} bytes  sha256 ${sha(s)}`);
  }
}
