/* build-byo.js — GENERATE mfg-lab/byo.html from the certified kernel.
 *
 * Same discipline as build-lab.js and mfg-cap's build-artifact: the page runs
 * the SAME solver the battery validates, so it is embedded VERBATIM and a gate
 * (test-byo-artifact.js) asserts byte-identity + freshness. What the browser
 * solves is exactly what test-byo.js proved certified.
 *
 * NEVER edit mfg-lab/byo.html. Edit lab/mfg-byo.js or tools/byo-template.html
 * and re-run:  node mfg-lab/tools/build-byo.js
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');           // mfg-lab/tools -> academic (or tree root)
const KERNEL = path.join(ROOT, 'mfg-lab', 'lab', 'mfg-byo.js');
const TEMPLATE = path.join(ROOT, 'mfg-lab', 'tools', 'byo-template.html');
const OUT = path.join(ROOT, 'mfg-lab', 'byo.html');
const MARKER = '/*__ENGINE__*/';
const sha = b => crypto.createHash('sha256').update(b).digest('hex');

function build() {
  const template = fs.readFileSync(TEMPLATE, 'utf8');
  if (template.indexOf(MARKER) < 0) throw new Error('template missing ' + MARKER);
  const src = fs.readFileSync(KERNEL, 'utf8');
  const engine =
`/* ── GENERATED by mfg-lab/tools/build-byo.js — DO NOT EDIT THIS FILE ──
   The kernel below is embedded VERBATIM from mfg-lab/lab/mfg-byo.js
   (sha256:${sha(fs.readFileSync(KERNEL)).slice(0, 16)}), so the browser runs
   byte-identically what mfg-lab/tests/test-byo.js validated. */
window.__mfgbyo = (function(){
var module = {exports:{}}, exports = module.exports;
/*<<<BEGIN mfg-byo.js>>>*/
${src}
/*<<<END mfg-byo.js>>>*/
return module.exports;
})();`;
  return template.replace(MARKER, engine);
}

const html = build();
if (require.main === module) {
  fs.writeFileSync(OUT, html);
  console.log('wrote ' + path.relative(ROOT, OUT) + '  ' + html.length + ' bytes  sha256:' + sha(html).slice(0, 16));
}
module.exports = { build, OUT, TEMPLATE, KERNEL, sha, MARKER };
