/* build-lab.js — GENERATE mfg-lab/lab.html from the instrument sources.

   WHY GENERATED AND NOT WRITTEN. The page runs the same instruments the
   batteries validate and the Python package mirrors. If the page carried its
   own copy, the three would drift and every certificate the page printed would
   slowly stop being evidence — which is the failure this repository has
   catalogued more than once and which `eqcert/tests/test-single-source.js`
   exists to prevent one level down. So the modules are EMBEDDED VERBATIM, and
   `mfg-lab/tests/test-lab-artifact.js` asserts byte-identity plus freshness.
   Same pattern as `mfg-cap/tools/build-artifact.js`.

   NEVER EDIT mfg-lab/lab.html. Edit the modules or the template and re-run:

       node mfg-lab/tools/build-lab.js

   HOW THE MODULES SURVIVE THE TRIP. They are CommonJS — they `require` each
   other and assign to `module.exports`. Rewriting them for the browser would
   destroy byte-identity, which is the whole point, so instead each source is
   wrapped UNTOUCHED in a function that supplies a `module`, an `exports` and a
   tiny `require` resolving by basename. The bytes between the wrapper lines are
   exactly the bytes on disk, and the gate checks that.
*/
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');            // mfg-lab/tools -> repo root
const OUT = path.join(ROOT, 'mfg-lab', 'lab.html');
const TEMPLATE = path.join(ROOT, 'mfg-lab', 'tools', 'lab-template.html');

/* Order matters: a module is defined before anything that requires it. */
const MODULES = [
  ['certificate.js', path.join(ROOT, 'eqcert', 'src', 'certificate.js')],
  ['contract.js', path.join(ROOT, 'mfg-lab', 'lab', 'contract.js')],
  ['order-study.js', path.join(ROOT, 'mfg-lab', 'lab', 'order-study.js')],
  ['failure-map.js', path.join(ROOT, 'mfg-lab', 'lab', 'failure-map.js')]
];

const MARKER = '/*__ENGINE__*/';

function sha(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

function build() {
  const template = fs.readFileSync(TEMPLATE, 'utf8');
  if (template.indexOf(MARKER) < 0) throw new Error('template is missing the ' + MARKER + ' marker');

  const parts = [];
  parts.push(`/* ── GENERATED by mfg-lab/tools/build-lab.js — DO NOT EDIT THIS FILE ──
   Every module below is embedded VERBATIM from its source on disk, so the code
   your browser runs is byte-identical to the code the batteries validate and
   the Python twin is held against. mfg-lab/tests/test-lab-artifact.js fails if
   any copy drifts or if this file is stale.
   Sources:
${MODULES.map(([n, p]) => '     ' + path.relative(ROOT, p) + '  sha256:' + sha(fs.readFileSync(p)).slice(0, 16)).join('\n')}
*/
var __labModules = {};
function __labRequire(spec){
  var key = spec.split('/').pop();
  if (!(key in __labModules)) throw new Error('module not bundled: ' + spec);
  return __labModules[key];
}`);

  for (const [name, file] of MODULES) {
    const src = fs.readFileSync(file, 'utf8');
    parts.push(
      `__labModules[${JSON.stringify(name)}] = (function(){\n` +
      `var module = {exports:{}}, exports = module.exports, require = __labRequire;\n` +
      `/*<<<BEGIN ${name}>>>*/\n` +
      src +
      `\n/*<<<END ${name}>>>*/\n` +
      `return module.exports;\n})();`
    );
  }

  parts.push(`window.__lab = {
  study: __labModules['order-study.js'].study,
  map: __labModules['failure-map.js'].map,
  validate: __labModules['contract.js'].validate,
  Certificate: __labModules['certificate.js'].Certificate,
  RESOLUTION: __labModules['order-study.js'].RESOLUTION
};`);

  return template.replace(MARKER, parts.join('\n\n'));
}

const html = build();

/* `require.main === module` matters. A freshness gate that imports its own
   builder, where the builder writes on import, silently REPAIRS the staleness
   it exists to detect — and this project shipped exactly that bug once, in a
   generated artifact elsewhere in the tree. Importing this file must never
   write. */
if (require.main === module) {
  fs.writeFileSync(OUT, html);
  console.log('wrote ' + path.relative(ROOT, OUT) + '  ' + html.length + ' bytes  sha256:' + sha(html).slice(0, 16));
}

module.exports = { build, MODULES, OUT, TEMPLATE, sha };
